apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: test-app
  name: client-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: client
  template:
    metadata:
      name: client-pods
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: panwazii/kpc:client
          env:
            - name: NUXT_PUBLIC_API_BASE
              value: http://52.77.157.4/api
---
apiVersion: v1
kind: Service
metadata:
  # namespace: test-app
  name: client-service
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
